export const PHASES = [
  {
    id: 1,
    title: "Phase 1 — Starter Node",
    goal: 8500,
    raised: 0,
    timeline: "Month 1–2",
    color: "#10b981",
    icon: "🌱",
    urgency: "LAUNCH THIS FIRST on Experiment.com",
    desc: "One refurbished compute server. Can already run BWA-MEM2, GATK, Snakemake pipelines.",
    items: [
      { name: "Refurbished Dell R6525 (AMD EPYC 7313, 16c)", cost: 1800 },
      { name: "256 GB DDR4 ECC RAM (8× 32 GB used)", cost: 900 },
      { name: "4× 4 TB NVMe SSD (Samsung 980 Pro)", cost: 800 },
      { name: "10 GbE NIC (Mellanox ConnectX-4)", cost: 200 },
      { name: "UPS (APC 1500VA)", cost: 280 },
      { name: "OS, cables, rack shelf", cost: 320 },
      { name: "1-year cloud backup (Backblaze B2)", cost: 120 },
      { name: "Shipping to Dhaka + import duties (~30%)", cost: 2400 },
      { name: "Experiment.com platform fee (8%)", cost: 680 },
      { name: "Contingency buffer (10%)", cost: 1000 },
    ],
    unlocks: ["BWA-MEM2 / STAR alignment", "GATK4 variant calling", "FastQC / MultiQC", "Snakemake / Nextflow", "BLAST / Diamond", "~20 WGS samples/day"],
  },
  {
    id: 2,
    title: "Phase 2 — Small Cluster",
    goal: 22000,
    raised: 0,
    timeline: "Month 3–6",
    color: "#3b82f6",
    icon: "🔬",
    urgency: "Launch after Phase 1 succeeds",
    desc: "Add a second compute node + shared NAS storage. Run parallel pipelines, scRNA-seq.",
    items: [
      { name: "Refurbished Dell R6525 (AMD EPYC 7443, 24c)", cost: 2800 },
      { name: "512 GB DDR4 ECC RAM", cost: 1600 },
      { name: "TrueNAS server + 8× 12 TB HDD (96 TB raw)", cost: 4200 },
      { name: "25 GbE switch (Mikrotik CRS305)", cost: 380 },
      { name: "Additional NVMe SSDs × 4", cost: 800 },
      { name: "SLURM + BeeGFS setup & admin (3 months)", cost: 2400 },
      { name: "Shipping + import duties", cost: 3200 },
      { name: "Experiment.com fee + contingency", cost: 2100 },
      { name: "Power conditioning / stabilizer", cost: 450 },
      { name: "Annual maintenance reserve", cost: 4070 },
    ],
    unlocks: ["scRNA-seq (Seurat/Scanpy)", "Metagenomics (Kraken2/MetaPhlAn)", "Trinity de novo assembly", "Multi-sample GWAS", "~60 WGS samples/day", "2-node SLURM queue"],
  },
  {
    id: 3,
    title: "Phase 3 — GPU Accelerated",
    goal: 45000,
    raised: 0,
    timeline: "Month 7–18",
    color: "#f59e0b",
    icon: "⚡",
    urgency: "Apply for grants + international donors",
    desc: "Add GPU node for AlphaFold2, DeepVariant, AI-based pathogen surveillance.",
    items: [
      { name: "Used A100 40 GB PCIe GPU × 2 (eBay / LambdaLabs)", cost: 14000 },
      { name: "GPU workstation (Supermicro AS-4124GS)", cost: 6500 },
      { name: "512 GB RAM + NVMe for GPU node", cost: 2200 },
      { name: "InfiniBand HDR switch (used/refurb)", cost: 5800 },
      { name: "Shipping + import (GPU classified as research equipment)", cost: 5500 },
      { name: "Annual NVIDIA Parabricks license", cost: 2500 },
      { name: "IT staff training (bioinformatics HPC)", cost: 2000 },
      { name: "Infrastructure / cooling upgrade", cost: 3500 },
      { name: "Platform fees + contingency", cost: 3000 },
    ],
    unlocks: ["AlphaFold2/3 protein prediction", "DeepVariant deep learning caller", "AI-based antimicrobial resistance", "COVID / dengue surveillance ML", "scRNA GPU acceleration (RAPIDS)", "~200 WGS samples/day"],
  },
  {
    id: 4,
    title: "Phase 4 — Full Production HPC",
    goal: 150000,
    raised: 0,
    timeline: "Year 2–3",
    color: "#8b5cf6",
    icon: "🚀",
    urgency: "Institutional grants (Wellcome, Gates, NIH Fogarty)",
    desc: "Scale to full cluster matching original spec. Serve multiple universities across Bangladesh.",
    items: [
      { name: "4× compute nodes (EPYC 9554 dual socket)", cost: 45000 },
      { name: "2× GPU nodes (H100 SXM5 ×4)", cost: 56000 },
      { name: "Parallel storage (Lustre, 576 TB)", cost: 18000 },
      { name: "HDR InfiniBand fabric", cost: 12000 },
      { name: "Professional rack + power + UPS", cost: 9000 },
      { name: "Import duties + installation", cost: 10000 },
    ],
    unlocks: ["National genomics infrastructure", "Regional disease surveillance hub", "AI drug discovery", "International collaboration node", "Open access for all BD universities"],
  },
];

export const PLATFORMS = [
  {
    name: "Experiment.com",
    icon: "🧪",
    type: "Science-specific",
    fee: "8%",
    best: "Phase 1 & 2",
    color: "#10b981",
    tip: "Best for Phase 1. Science audience, high credibility. All-or-nothing model means donors trust you won't pocket partial funds.",
    url: "https://experiment.com",
  },
  {
    name: "GoFundMe",
    icon: "💙",
    type: "General public",
    fee: "0% + payment fees",
    best: "Phase 1 & 2",
    color: "#3b82f6",
    tip: "Share in Bangladeshi diaspora communities (UK, USA, Canada). Tell the human story: diseases, patients, local researchers.",
    url: "https://gofundme.com",
  },
  {
    name: "Indiegogo",
    icon: "💡",
    type: "Tech community",
    fee: "5%",
    best: "Phase 2 & 3",
    color: "#f59e0b",
    tip: "Use InDemand mode after initial goal — keep collecting indefinitely. Good for tech-savvy international donors.",
    url: "https://indiegogo.com",
  },
  {
    name: "Open Collective",
    icon: "🤝",
    type: "Open source / research",
    fee: "10%",
    best: "Phase 2–4",
    color: "#8b5cf6",
    tip: "Transparent fund management. Great for institutional donors who want audit trails. Register as a Fiscal Host.",
    url: "https://opencollective.com",
  },
];

export const GRANTS = [
  { org: "Wellcome Trust", program: "Developing Countries Initiative", amount: "$50K–$500K", fit: "⭐⭐⭐⭐⭐", note: "Specifically funds LMIC bioinformatics infrastructure" },
  { org: "NIH Fogarty International", program: "D43 Training Grants", amount: "$100K–$300K", fit: "⭐⭐⭐⭐⭐", note: "Bangladesh qualifies as LMIC. HPC training component." },
  { org: "Gates Foundation", program: "Grand Challenges", amount: "$100K+", fit: "⭐⭐⭐⭐", note: "Disease surveillance, AMR, pathogen genomics" },
  { org: "H3ABioNet", program: "African / Asian Bioinformatics Network", amount: "Equipment grants", fit: "⭐⭐⭐⭐", note: "Bioinformatics capacity building in LMICs" },
  { org: "IDRC Canada", program: "Open Science Fund", amount: "CAD 50K–150K", fit: "⭐⭐⭐⭐", note: "Bangladesh eligible. Research infrastructure." },
  { org: "AWS Research Credits", program: "AWS Research Credits", amount: "$10K–$100K cloud", fit: "⭐⭐⭐⭐⭐", note: "FREE cloud HPC while physical cluster is funded. Apply immediately." },
  { org: "Google TPU Research Cloud", program: "TRC Program", amount: "Free GPU/TPU time", fit: "⭐⭐⭐⭐⭐", note: "Free compute for AlphaFold/ML immediately — no cost." },
  { org: "Bangladesh UGC", program: "Research Grant (বিশ্ববিদ্যালয় মঞ্জুরি কমিশন)", amount: "BDT 5–20 Lakh", fit: "⭐⭐⭐", note: "Apply through your university department." },
];

export const DONOR_TIERS = [
  { amount: 10, title: "Supporter", icon: "🌾", reward: "Name in README + digital thank-you certificate", count: "Need 50+" },
  { amount: 50, title: "Lab Friend", icon: "🔬", reward: "All above + mention in first publication acknowledgements", count: "Need 40+" },
  { amount: 200, title: "Genome Patron", icon: "🧬", reward: "All above + acknowledgement in methods paper", count: "Need 20+" },
  { amount: 500, title: "Sequence Sponsor", icon: "⚡", reward: "All above + named server partition + priority access", count: "Need 8+" },
];
